baseURL: https://notis-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Notis Lapatas
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Find out more
    subtitle: |-
      London business school MFA 2023.
    title: Hi, my name is Notis Lapatas
  blog: {This is my personal blog}
  contact:
    address:
      - city: london, NW1 6XE
        country: United Kingdom 
        street: Baker street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: notisdet@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (30) 6948844890
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Notis Lapatas
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/Notis-lp
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/notis-lapatas
  image: ''
  name: Notis
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Lapatas
    title: Notis
  tiles:
    enable: yes
    showcase:
      - image: DSC05667-Edit.jpg
        subtitle: 
        title: Work experience
        url: blogs/aliquam
      - image: DSC00870.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: DJI_0132.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: IMG_20220926_185613.jpg
        subtitle: Nisl Sed Aliquam
        title: LBS
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
