baseURL: https://notis-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Notis Lapatas
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Find out more
    subtitle: |-
      London business school MFA 2023.
    title: Hi, my name is Notis Lapatas
  blog: {This is my personal blog}
  contact:
    address:
      - city: london, NW1 6XE
        country: United Kingdom 
        street: Baker street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: notisdet@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (30) 6948844890
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Notis Lapatas
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/Notis-lp
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/notis-lapatas
  image: ''
  name: Notis
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Lapatas
    title: Notis
  tiles:
    enable: yes
    showcase:
      - image: DSC09764.jpg
        subtitle: Markets
        title: Project
        url: blogs/risk_return
      - image: DSC00870.jpg
        subtitle: Feugiat Amet Tempus
        title: Work experience
        url: blogs/tempus
      - image: IMG_20220926_185613.jpg
        subtitle: Work experience
        title: Education
        url: blogs/magna
      - image: pic06.jpg
        subtitle: Speeches & Awards
        title: Conferences
        url: blogs/ipsum
      - image: DSC00870.jpg
        subtitle: photography, cars & coffee
        title: Hobbies
        url: blogs/ipsum
      - image: DSC05667-Edit.jpg
        subtitle: 
        title: About me
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "I am a versatile individual with a passion for 
    finance, cars, and photography. As a financial analyst, I provide valuable
    insights and assist businesses in making sound financial decisions through 
    my expertise in market trends, investment strategies, and financial modeling.
Beyond finance, my unwavering love for cars drives me to immerse myself in the 
world of automobiles. From classic models to cutting-edge designs, I attend car 
shows, engage in automotive discussions, and share my thoughts on the latest
industry developments.
\n Photography is another creative outlet that I cherish deeply. Through my lens, 
I capture fleeting moments, stunning landscapes, and candid portraits, reflecting 
my unique perspective and storytelling abilities.
\n On this website, you will find a collection of my professional achievements, 
financial analyses, and recommendations, along with glimpses into my car-related 
adventures and captivating photographs. Whether you seek financial insights, 
car-related content, or visual storytelling, I invite you to explore my portfolio 
and experience the diverse facets of my passion-driven journey."
    title: Who is Notis?
    url: blogs
