baseURL: https://notis-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Notis Lapatas
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Find out more
    subtitle: |-
      London business school MFA 2023.
    title: Hi, my name is Notis Lapatas
  blog: {This is my personal blog}
  contact:
    address:
      - city: london, NW1 6XE
        country: United Kingdom 
        street: Baker street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: notisdet@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (30) 6948844890
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Notis Lapatas
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/Notis-lp
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/notis-lapatas
  image: ''
  name: Notis
  navigation:
    button1:
      - name: Git Hub
        url: https://github.com/Notis-lp
    button2:
      - name: LinkdIn
        url: https://www.linkedin.com/in/notis-lapatas
    links:
      - name: Home
        url: '#'
      - name: CV
        url: blogs/cv
      - name: About me
        url: 
    menu: Menu
    subtitle: Lapatas
    title: Notis
  tiles:
    enable: yes
    showcase:
      - image: DSC09764.jpg
        subtitle: Markets
        title: Project
        url: blogs/risk_return
      - image: pic06.jpg
        subtitle: 
        title: Work experience
        url: blogs/work
      - image: IMG_20220926_185613.jpg
        subtitle: 
        title: Education
        url: blogs/education
      - image: IMG_4789.jpg
        subtitle: Speeches & Awards
        title: Achievements
        url: blogs/achievements
      - image: DSC00870.jpg
        subtitle: photography, cars & coffee
        title: Hobbies
        url: blogs/hobbies
      - image: DSC05667-Edit.jpg
        subtitle: 
        title: About me
        url: blogs/about
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "On this website, you will find a collection of my professional achievements, 
financial analyses, and recommendations, along with glimpses into my car-related 
adventures and captivating photographs. Whether you seek financial insights, 
car-related content, or visual storytelling, I invite you to explore my portfolio 
and experience the diverse facets of my passion-driven journey."
    title: Who is Notis?
    url: blogs
