[build]
  publish = "public"
  command = "hugo" 34
  
[build.environment]
  HUGO_VERSION = "0.111.3"
  HUGO_ENABLEGITINFO = "true" 78
  
[context.production.environment]
  HUGO_ENV = "production"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.111.3"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.111.3"
